SENSOR_F_S_L_ADDRESS = 0x0
SENSOR_F_S_R_ADDRESS = 0x0
SENSOR_R_S_F_ADDRESS = 0x0
SENSOR_R_S_B_ADDRESS = 0x0
SENSOR_B_S_R_ADDRESS = 0x0
SENSOR_B_S_L_ADDRESS = 0x0
SENSOR_L_S_B_ADDRESS = 0x0
SENSOR_L_S_F_ADDRESS = 0x0
