SENSOR_F_S_L_ADDRESS = 0x5A
SENSOR_F_S_R_ADDRESS = 0x5E
SENSOR_R_S_F_ADDRESS = 0x5C
SENSOR_R_S_B_ADDRESS = 0x7A
SENSOR_B_S_R_ADDRESS = 0x5F
SENSOR_B_S_L_ADDRESS = 0x6C
SENSOR_L_S_B_ADDRESS = 0x6B
SENSOR_L_S_F_ADDRESS = 0x5B

SENSOR_F_S_L_PIN = 11
SENSOR_F_S_R_PIN = 13
SENSOR_R_S_F_PIN = 12
SENSOR_R_S_B_PIN = 18
SENSOR_B_S_R_PIN = 17
SENSOR_B_S_L_PIN = 9
SENSOR_L_S_B_PIN = 27
SENSOR_L_S_F_PIN = 5
