SENSOR_F_S_L_ADDRESS = 0x6C
SENSOR_F_S_R_ADDRESS = 0x5A
SENSOR_R_S_F_ADDRESS = 0x5B
SENSOR_R_S_B_ADDRESS = 0x5C
SENSOR_B_S_R_ADDRESS = 0x5E
SENSOR_B_S_L_ADDRESS = 0x5F
SENSOR_L_S_B_ADDRESS = 0x7A
SENSOR_L_S_F_ADDRESS = 0x6B

SENSOR_F_S_L_PIN = 9
SENSOR_F_S_R_PIN = 11
SENSOR_R_S_F_PIN = 5
SENSOR_R_S_B_PIN = 12
SENSOR_B_S_R_PIN = 13
SENSOR_B_S_L_PIN = 17
SENSOR_L_S_B_PIN = 18
SENSOR_L_S_F_PIN = 27
